/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mod {
  'id' : bigint,
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'downloadUrl' : string,
  'author' : string,
  'category' : string,
  'image' : string,
}
export interface _SERVICE {
  'addMod' : ActorMethod<
    [string, string, string, Array<string>, string, string, string],
    bigint
  >,
  'deleteMod' : ActorMethod<[bigint], boolean>,
  'getMods' : ActorMethod<[], Array<Mod>>,
  'updateMod' : ActorMethod<
    [bigint, string, string, string, Array<string>, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];